### ISSUE TITLE
Make a Snapcraft Snap

### ISSUE THREAD

**Issue by nektro** [nektro/andesite#27]
https://snapcraft.io/

**Comment by riptl** [comment]
I recommend using [Git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) for automated tagging with Snapcraft and Docker.

Sample `snapcraft.yaml`:

```yaml
name: andesite
version: git
summary: Easily manage access to your open directory through OAuth2.
description: |
  Share folders in an Open Directory without making your entire server public. Manages users with OAuth2.
parts:
  andesite:
    plugin: go
    go-importpath: github.com/nektro/andesite
    source: .
    source-type: git
    build-packages:
      - gcc
```

**Comment by nektro** [comment]
I was able to find that from https://snapcraft.io/first-snap. Would adding a default launch argument be similar to this?
```yaml
apps:
  andesite:
    command: bin/andesite --use-env true
```
I was unclear from the Snap docs whether or not this adds a command to the PATH or is the launch path for the registered daemon.
